# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=10)),
                ('receiver_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=50)),
                ('id_required', models.BooleanField(default=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.Client')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.Branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.AddField(
            model_name='driver',
            name='warehouse_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.WarehouseManager'),
        ),
    ]
