# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0002_auto_20161001_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousemanager',
            name='branch',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='destination',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='receiver_name',
            new_name='client_city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='warehouse_manager',
        ),
        migrations.RemoveField(
            model_name='package',
            name='client',
        ),
        migrations.AddField(
            model_name='driver',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='surname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='WarehouseManager',
        ),
    ]
