# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20161001_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license_number',
            new_name='driver_id',
        ),
    ]
